### ISSUE TITLE
fresh installed but  Graylog Web Interface is disconnected.

### ISSUE THREAD

**Issue by hepin1989** [Graylog2/omnibus-graylog2#13]
Graylog Web Interface is disconnected.

The web interface could not connect to any of the Graylog nodes it has been connected to before.
Please check that the servers shown to the right are running and reachable.

**Comment by hepin1989** [comment]
ubuntu 14.04.3

**Comment by hepin1989** [comment]
with 
```
netstat anp|grep 12900
```
output
```
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
getnameinfo failed
tcp6       0      0 [未知]:58566          [未知]:12900          TIME_WAIT  
tcp6       0      0 [未知]:58495          [未知]:12900          TIME_WAIT 
```

**Comment by hepin1989** [comment]
after restart the pc,works.

**Comment by hepin1989** [comment]
I think it would be great that graylog2 with some diagnosis support.

**Comment by mariussturm** [comment]
What exactly do you need? Without any logs or detailed informations it's hard to say what went wrong in your case.

**Comment by hepin1989** [comment]
@mariussturm It seems like the socket is not released so after I restart the server ,it just works.

I haven't look into that code,maybe ReuseAddr would help:)

anyway it works now. thanks.

**Comment by hepin1989** [comment]
```
2015-08-13_04:51:21.40102 INFO  [transport] [graylog2-server] bound_address {inet[/0:0:0:0:0:0:0:0:9350]}, publish_address {inet[/192.168.0.125:9350]}
2015-08-13_04:51:21.41583 INFO  [discovery] [graylog2-server] graylog2/As5OyaPBQaagPjMg0w8QpA
2015-08-13_04:51:21.54902 INFO  [Reflections] Reflections took 327 ms to scan 1 urls, producing 2 keys and 2 values 
2015-08-13_04:51:24.41620 WARN  [discovery] [graylog2-server] waited for 3s and no initial state was set by the discovery
2015-08-13_04:51:24.41644 INFO  [node] [graylog2-server] started
2015-08-13_04:51:25.70689 INFO  [RestApiService] Adding security context factory: <org.graylog2.security.ShiroSecurityContextFactory@5e217eba>
2015-08-13_04:51:25.72352 INFO  [RestApiService] Started REST API at <http://0.0.0.0:12900/>
2015-08-13_04:51:29.41803 ERROR [UI] 
2015-08-13_04:51:29.41805 
2015-08-13_04:51:29.41806 ################################################################################
2015-08-13_04:51:29.41808 
2015-08-13_04:51:29.41808 ERROR: Could not successfully connect to Elasticsearch, if you use multicast check that it is working in your network and that Elasticsearch is running properly and is reachable. Also check that the cluster.name setting is correct.
2015-08-13_04:51:29.41808 
2015-08-13_04:51:29.41809 Need help?
2015-08-13_04:51:29.41809 
2015-08-13_04:51:29.41809 * Official documentation: http://docs.graylog.org/
2015-08-13_04:51:29.41809 * Community support: https://www.graylog.org/community-support/
2015-08-13_04:51:29.41810 * Commercial support: https://www.graylog.com/support/
2015-08-13_04:51:29.41810 
2015-08-13_04:51:29.41810 But we also got some specific help pages that might help you in this case:
2015-08-13_04:51:29.41810 
2015-08-13_04:51:29.41811 * http://docs.graylog.org/en/1.0/pages/configuring_es.html
2015-08-13_04:51:29.41811 
2015-08-13_04:51:29.41811 Terminating. :(
2015-08-13_04:51:29.41811 
2015-08-13_04:51:29.41812 ################################################################################
2015-08-13_04:51:29.41812 
2015-08-13_04:51:29.42346 ERROR [ServiceManager] Service IndexerSetupService [FAILED] has failed in the STARTING state.
2015-08-13_04:51:29.42349 java.lang.IllegalStateException
2015-08-13_04:51:29.42349 	at org.graylog2.UI.exitHardWithWall(UI.java:36)
2015-08-13_04:51:29.42350 	at org.graylog2.initializers.IndexerSetupService.startUp(IndexerSetupService.java:185)
2015-08-13_04:51:29.42350 	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
2015-08-13_04:51:29.42350 	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
2015-08-13_04:51:29.42350 	at java.lang.Thread.run(Thread.java:745)
2015-08-13_04:51:29.42460 ERROR [InputSetupService] Not starting any inputs because lifecycle is: Uninitialized?[LB:DEAD]
2015-08-13_04:51:29.42868 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.AlertScannerThread].
2015-08-13_04:51:29.42872 INFO  [RestApiService] Shutting down REST API at <http://0.0.0.0:12900/>
2015-08-13_04:51:29.42885 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.AlertScannerThread] complete, took <0ms>.
2015-08-13_04:51:29.42892 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread].
2015-08-13_04:51:29.42896 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] complete, took <0ms>.
2015-08-13_04:51:29.42900 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.ClusterHealthCheckThread].
2015-08-13_04:51:29.42905 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.ClusterHealthCheckThread] complete, took <0ms>.
2015-08-13_04:51:29.42909 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.IndexerClusterCheckerThread].
2015-08-13_04:51:29.42913 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.IndexerClusterCheckerThread] complete, took <0ms>.
2015-08-13_04:51:29.42917 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.IndexRetentionThread].
2015-08-13_04:51:29.42921 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.IndexRetentionThread] complete, took <0ms>.
2015-08-13_04:51:29.42925 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.IndexRotationThread].
2015-08-13_04:51:29.42930 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.IndexRotationThread] complete, took <0ms>.
2015-08-13_04:51:29.42934 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.VersionCheckThread].
2015-08-13_04:51:29.42938 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.VersionCheckThread] complete, took <0ms>.
2015-08-13_04:51:29.42942 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.ThrottleStateUpdaterThread].
2015-08-13_04:51:29.42946 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.ThrottleStateUpdaterThread] complete, took <0ms>.
2015-08-13_04:51:29.42950 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.events.ClusterEventPeriodical].
2015-08-13_04:51:29.42954 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.events.ClusterEventPeriodical] complete, took <0ms>.
2015-08-13_04:51:29.42958 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.events.ClusterEventCleanupPeriodical].
2015-08-13_04:51:29.42963 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.events.ClusterEventCleanupPeriodical] complete, took <0ms>.
2015-08-13_04:51:29.42966 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.PurgeExpiredCollectorsThread].
2015-08-13_04:51:29.42971 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.PurgeExpiredCollectorsThread] complete, took <0ms>.
2015-08-13_04:51:29.42974 INFO  [PeriodicalsService] Shutting down periodical [org.graylog.plugins.usagestatistics.UsageStatsNodePeriodical].
2015-08-13_04:51:29.42979 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog.plugins.usagestatistics.UsageStatsNodePeriodical] complete, took <0ms>.
2015-08-13_04:51:29.42982 INFO  [PeriodicalsService] Shutting down periodical [org.graylog.plugins.usagestatistics.UsageStatsClusterPeriodical].
2015-08-13_04:51:29.42986 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog.plugins.usagestatistics.UsageStatsClusterPeriodical] complete, took <0ms>.
2015-08-13_04:51:29.43295 WARN  [BufferSynchronizerService] Elasticsearch is unavailable. Not waiting to clear buffers and caches, as we have no healthy cluster.
2015-08-13_04:51:29.43325 INFO  [node] [graylog2-server] stopping ...
2015-08-13_04:51:29.43328 INFO  [OutputSetupService] Stopping output org.graylog2.outputs.BlockingBatchedESOutput
2015-08-13_04:51:29.44685 INFO  [node] [graylog2-server] stopped
2015-08-13_04:51:29.44695 INFO  [node] [graylog2-server] closing ...
2015-08-13_04:51:29.45144 INFO  [node] [graylog2-server] closed
2015-08-13_04:51:29.50995 INFO  [JournalReader] Stopping.
2015-08-13_04:51:29.51020 INFO  [ServiceManagerListener] Services are now stopped.
2015-08-13_04:51:29.51047 ERROR [ServerBootstrap] Graylog startup failed. Exiting. Exception was:
2015-08-13_04:51:29.51048 java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {FAILED=[IndexerSetupService [FAILED]]}
2015-08-13_04:51:29.51049 	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:710)
2015-08-13_04:51:29.51049 	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:535)
2015-08-13_04:51:29.51049 	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:301)
2015-08-13_04:51:29.51049 	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:114)
2015-08-13_04:51:29.51049 	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:196)
2015-08-13_04:51:29.51050 	at org.graylog2.bootstrap.Main.main(Main.java:58)
2015-08-13_04:51:29.51112 INFO  [Server] SIGNAL received. Shutting down.
2015-08-13_04:51:29.51389 INFO  [GracefulShutdown] Graceful shutdown initiated.
2015-08-13_04:51:29.51412 INFO  [GracefulShutdown] Node status: [Halting?[LB:DEAD]]. Waiting <3sec> for possible load balancers to recognize state change.
2015-08-13_04:51:33.51604 INFO  [GracefulShutdown] Goodbye.

```

**Comment by mariussturm** [comment]
Thanks for the logs. Elasticsearch is not running on your box. Usually this happens because of insuffcient memory settings. Do you have at least 4GB ram in this box?
In doubt please send the Elasticsearch logs from /var/log/graylog/elasticsearch/current

**Comment by ajpen** [comment]
@mariussturm how much RAM recommended should be dedicated to Elasticsearch?

**Comment by mariussturm** [comment]
@ajpen this highly depends on the message throughput but you can calculate 4-16gb ram for a dedicated ES node. Check also our setup size estimator: https://www.graylog.org/tools/sizing-estimator
